### ISSUE TITLE
No such file or directory error: library.yml

### ISSUE THREAD

**Issue by matt8s** [mnishida/RII_Pandas#9]
I installed the latest version (0.6.16) of RII_Pandas using pip on Windows. When I tried to run RII_Pandas for the first time and build the database, I got the following error:

>>> import riip
>>> ri = riip.RiiDataFrame()
Catalog file not found.
Cloning Repository...
Done.
Creating catalog file...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\riip\dataframe.py", line 113, in __init__
    _catalog, _raw_data = self._load_catalog_and_raw_data()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\riip\dataframe.py", line 133, in _load_catalog_and_raw_data
    catalog = self._add_my_db_to_catalog(self._create_catalog())
                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\riip\dataframe.py", line 222, in _create_catalog
    list(self._extract_entry(self._db_path)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\riip\dataframe.py", line 167, in _extract_entry
    with open(library_file, "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python311\\Lib\\site-packages\\riip\\data\\refractiveindex.info-database\\database\\library.yml'

This may be because the Polyanskiy directory now has library-nk.yml and library-n2.yml files, instead of a library.yml file.

**Comment by mnishida** [comment]
Thank you for your report. This issue has been fixed in v0.7.0.
